### PR TITLE
Feature/sorting

### PR DESCRIPTION
**Pull request by justjustie**
Kinda contains #11, therefore fixes the font and adds sorting to the lexicon

### CODE REVIEW

**Review by dylanpiera — COMMENTED** [review]
Font stuff is fine, will test the sorting feature (hopefully) tonight and then I'll approve if it works.

**Comment by justjustie** [comment]
Im gonna close the font PR #11 then since it is integrated here

**Review by dylanpiera — CHANGES_REQUESTED** [review]
Couple of things:

While sorting by number works, it doesn't take negatives into account, and just goes by the biggest number. I'm not entirely sure if this is a true problem, as how often are we gonna sort by an artificial number anyways, but have you tested it with letters? 

image
image


Also it's very unintuitive that the option of sorting is there, could you make sure that it's more obvious that the option is there?

**Comment by justjustie** [comment]
So we now have case insensitive sorting and the feature is a little more visible.
Sorting strings starting with negative numbers mathematically wouldn't really be practical to implement, also I don't think that's really nessecary

**Review by dylanpiera — APPROVED** [review]

**Pull request merged**
